#!/usr/bin/env bash
# ZenTaoPMS 一键启动开发服务器
#
# 用法：
#   ./dev.sh              # 默认 8080 端口
#   PORT=9000 ./dev.sh    # 自定义端口
#
# 功能：
#   - 自动初始化数据库（首次运行）
#   - 自动杀掉占用端口的旧进程
#   - 启动 PHP 内置服务器（www 为 docroot）
#   - 实时打印请求日志
#   - Ctrl-C 干净退出
#
# 默认管理员账号：admin / Admin1234!
#
# 环境变量：
#   PORT              服务器端口（默认 8080）
#   HOST              服务器地址（默认 127.0.0.1）
#   DB_HOST           MySQL 主机（默认 127.0.0.1）
#   DB_PORT           MySQL 端口（默认 3306）
#   DB_NAME           数据库名（默认 zentao）
#   DB_USER           应用账号（默认 zentao）
#   DB_PASSWORD       应用密码（默认 zentao123456）
#   DB_ROOT_USER      root 账号（默认 root）
#   DB_ROOT_PASSWORD  root 密码（默认空）
#   ADMIN_ACCOUNT     管理员账号（默认 admin）
#   ADMIN_PASSWORD    管理员密码（默认 Admin1234!）
#   PHP_WORKERS       PHP 内置服务器 worker 数（默认 8）

set -euo pipefail

PORT="${PORT:-8080}"
HOST="${HOST:-127.0.0.1}"
PHP_WORKERS="${PHP_WORKERS:-8}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-3306}"
DB_NAME="${DB_NAME:-zentao}"
DB_USER="${DB_USER:-zentao}"
DB_PASSWORD="${DB_PASSWORD:-zentao123456}"

PROJECT_ROOT="$(dirname "$(readlink -f "$0")")"
DOCROOT="$PROJECT_ROOT/www"
LOG_DIR="$PROJECT_ROOT/tmp/logs"
LOG_FILE="$LOG_DIR/dev-server.log"
PID_FILE="$LOG_DIR/dev-server.pid"

mkdir -p "$LOG_DIR"

# 终止旧进程
if [[ -f "$PID_FILE" ]]; then
    OLD_PID="$(cat "$PID_FILE" 2>/dev/null || true)"
    if [[ -n "$OLD_PID" ]] && kill -0 "$OLD_PID" 2>/dev/null; then
        echo "→ 终止旧进程 PID=$OLD_PID"
        kill "$OLD_PID" 2>/dev/null || true
        sleep 1
    fi
fi

# 也按端口查一遍（兜底）
EXISTING_PID="$(lsof -ti ":$PORT" 2>/dev/null || true)"
if [[ -n "$EXISTING_PID" ]]; then
    echo "→ 端口 $PORT 被占用，终止 PID=$EXISTING_PID"
    kill -9 $EXISTING_PID 2>/dev/null || true
    sleep 1
fi

# 前置检查
echo "→ 检查环境"
command -v php >/dev/null || { echo "✗ 未找到 php，请先安装 PHP 8.1+"; exit 1; }
PHP_VER_OK="$(php -r 'echo PHP_VERSION_ID >= 80100 ? "yes" : "no";')"
[[ "$PHP_VER_OK" == "yes" ]] || { echo "✗ PHP 版本太低，需要 8.1+（当前 $(php -v | head -1)）"; exit 1; }

# 检查关键扩展
MISSING=()
for ext in pdo_mysql mbstring json curl gd iconv; do
    php -m 2>/dev/null | grep -qi "^$ext$" || MISSING+=("$ext")
done
if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo "⚠ 缺少扩展: ${MISSING[*]}（建议安装：sudo apt install php8.3-{pdo_mysql,mbstring,curl,gd}）"
fi

# 初始化数据库（首次运行时自动执行）
if command -v mysql >/dev/null; then
    "$PROJECT_ROOT/dev-init-db.sh"
else
    echo "⚠ 未找到 mysql 客户端，跳过数据库检查"
fi

# config/my.php may be generated by the Docker entrypoint. Make the local
# dev server use the same database values that dev-init-db.sh just prepared.
export ZT_INSTALLED="${ZT_INSTALLED:-true}"
export ZT_DEBUG="${ZT_DEBUG:-1}"
export ZT_DB_HOST="${ZT_DB_HOST:-$DB_HOST}"
export ZT_DB_PORT="${ZT_DB_PORT:-$DB_PORT}"
export ZT_DB_NAME="${ZT_DB_NAME:-$DB_NAME}"
export ZT_DB_USER="${ZT_DB_USER:-$DB_USER}"
export ZT_DB_PASSWORD="${ZT_DB_PASSWORD:-$DB_PASSWORD}"
export ZT_DB_PREFIX="${ZT_DB_PREFIX:-${DB_PREFIX:-zt_}}"
export ZT_DEFAULT_LANG="${ZT_DEFAULT_LANG:-zh-cn}"
export PHP_CLI_SERVER_WORKERS="$PHP_WORKERS"

# 启动服务器
echo "→ 启动 PHP 开发服务器 http://${HOST}:${PORT}/"
echo "  docroot: $DOCROOT"
echo "  log:     $LOG_FILE"
echo "  workers: $PHP_WORKERS"
echo "  默认账号：admin / Admin1234!"
echo "  按 Ctrl-C 停止"
echo ""

php -S "${HOST}:${PORT}" -t "$DOCROOT" >"$LOG_FILE" 2>&1 &
SERVER_PID=$!
echo "$SERVER_PID" > "$PID_FILE"

cleanup() {
    echo ""
    echo "→ 停止服务器 PID=$SERVER_PID"
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
    rm -f "$PID_FILE"
    echo "✓ 已退出"
}
trap cleanup EXIT INT TERM

# 等待服务器就绪
for i in {1..15}; do
    if curl -sI "http://${HOST}:${PORT}/" >/dev/null 2>&1; then
        echo "✓ 服务器就绪"
        break
    fi
    sleep 0.3
done

# 自动打开浏览器（可选）
# if command -v xdg-open >/dev/null && [[ -z "${NO_OPEN_BROWSER:-}" ]]; then
#     (sleep 1; xdg-open "http://${HOST}:${PORT}/" >/dev/null 2>&1) &
# fi

# 实时打印日志
tail -f "$LOG_FILE"
